group: edge
dist: trusty

env:
  global:
    TERM=dumb

language: java
jdk:
  - openjdk8
  - oraclejdk8

install: true
before_install:
  - sudo apt update

  # frontend tests
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb

  # install docker-compose
  - sudo apt install -y python-pip curl jq libxml2-utils
  - sudo pip install docker-compose httpie
  - sudo usermod -aG docker $(whoami)

  # daggerok bash functions
  - source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)

  # kill whatever punning on postgres / rabbitmq port
  - stop_any 5432 5672 27017

script:
  - bash gradlew clean build docs
  - export ROOT=$PWD
  - >
    for path in \
      keycloak-identity-management \
      csrf-protection-spa ;
    do
      export TARGET="$ROOT/$path"
      cd $TARGET
      bash gradlew clean assemble
      bash gradlew composeUp
      bash gradlew composeDown
    done;

#before_cache:
#  - bash gradlew --stop
#  - rm -rf $HOME/.gradle/caches/modules-2/modules-2.lock
#  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.m2/
    - $HOME/.gradle/
