service:
- docker

language: java
jdk: oraclejdk8

addons:
  apt:
    update: true
    packages:
    - google-chrome-stable
    - docker-ce
    - python-pip
    - curl
    - jq
    - libxml2-utils
    - libappindicator1
    - fonts-liberation

install: true
before_install:
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sudo pip install docker-compose httpie >/dev/null 2>&1
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 5432 5672 27017 8080 80

script:
- bash gradlew clean build asciidoctor >/dev/null
- export root=$(pwd)
#
- cp -Rf ${root}/spring-5-security-oauth2/spring-mvc-facebook/src/main/resources/config/application-facebook-default.yaml ${root}/spring-5-security-oauth2/spring-mvc-facebook/src/main/resources/config/application-facebook.yaml
- cp -Rf ${root}/spring-5-security-oauth2/spring-mvc-facebook-github/src/main/resources/config/application-oauth2-default.yaml ${root}/spring-5-security-oauth2/spring-mvc-facebook-github/src/main/resources/config/application-oauth2.yaml
- cp -Rf ${root}/spring-5-security-oauth2/spring-mvc-github/src/main/resources/config/application-github-default.yaml ${root}/spring-5-security-oauth2/spring-mvc-github/src/main/resources/config/application-github.yaml
#
- bash ./mvnw -f ${root}/spring-5-security-oauth2/pom.xml >/dev/null
- bash ./gradlew -b ${root}/spring-5-security-oauth2/build.gradle >/dev/null
#
- bash ${root}/spring-5-security-oauth2/spring-mvc-facebook/target/*.jar &
- wait_for 8080
- http :8080/login
- stop_any 8080 80
#
- bash ${root}/spring-5-security-oauth2/spring-mvc-github/build/libs/*.jar &
- wait_for 8080
- http :8080/login
- stop_any 8080 80
#
- bash ${root}/spring-5-security-oauth2/spring-mvc-facebook-github/build/libs/*.jar &
- wait_for 8080
- http :8080/login
- stop_any 8080 80
#
- >
  for path in \
    keycloak-identity-management \
    csrf-protection-spa ;
  do
    export TARGET="$root/$path"
    cd $TARGET
    bash gradlew clean assemble >/dev/null
    bash gradlew composeUp >/dev/null
    bash gradlew composeDown
  done;

before_cache:
- sudo rm -rf $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
- sudo rm -rf $HOME/.gradle/caches/*/fileHashes/fileHashes.lock
- sudo rm -rf $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
  - $HOME/.docker

env:
  global:
  - TERM=dumb
#  - secure: "sc34wHwsLTKMWTxLhfyWe7lbaYadcSAo0lyTxBdHinhH82ohWGVYpV7Zm3pbBH15BZ6V5pvqspgm2oNOExHBonZ1yhn3VUreso+4h+nf8mAwCjH+71MNTeuQo+d8Jky3SIeLvf4LqYZ6Zbf8yXksPF3DFG49M1S1KByIPmF+LT08pbZEptrsb+T6tuAIyWqMosx4Y4mKub9IgFjudtw42yd+sE4kihpVhW9ebw3wrZYtREXuZxIDfIvvjC+n5cEs0plm41725CVTv893WU6P3Kl0Gtkl6mER6HDLYPIKnSBrDFKvnmMSD7Sc3w/wPFaxfRayC4LB2til324+IcmFq8EeQ7mKRsEwQiIqWra8702/5v9+JH4JntO5lS8cs5osMEv7bf1+bI4+AFTb4S2PqjWFwuvts2yLOZ3tmpFMjHK666+Jaa63JBSVA4+Bhjn2+9hAeIVxhQuiT5oZ3fenHFC8cZV/ywDqjSWfzgoEWJNfiBAfl/ZQRgt1JBFSJrCVjaYIoqscj64L89KMzBu0wrkuepU3n4gJMGPX+7cv4CHcrzCXX3f3mpfiP58swfCh2bNNhuR1xCu7Yyus2UsFcrI5ell4b84Hl1nkY6pOZhr9cwiylSHkBM2TEZQlCRLqbATaFK8/4GpDcCjFey6tyrg6tqhflND+oiiR3WZQYo0="
#  - secure: "KJVdsTw/MXIfLTkVQdqrhi5XlE+puJc+FCkG6p5HC5vUSsb+Ws1v3jJs4U8TYEjf/vvvVlGU5VjoL6MUDb1VfTgTjyhm9bWzZGihgcTMsKpoIjV8sx55RJfTyp3i34qZlwdeQheKjzAMRlKKng3kPH7tW22sNfBRBSpWokYlDuKJfvKWLmvVqpJDyMcDSV9g1EyQRCPitVZrtE7zE2wJrL6DHuw0NzyuicNlK7t9gZaqNdndZtoKXa1akYu+2yDHFGsTwG7WnfM8doj1t7dwzP3Yp194iApGY0r/S0V25qkwA4kpWb4btkmcdDopnKxxiH8KUl+ipZqgOojpz/ybetxP8+kKeXCA1TPBYvKMlaiM5Hvszb6J5duYSDeblCJ3B2jLbwtnWlTHlLhZssWc7gkIjRmJHt+oNQVNdyjo/uqIkkrqUMhW/Gtp0QxEePjQVhKMsPP3L6+XAWvpsJqir/VRV4GQz4A1K9849U70xrWX2cAqC0Jtbp4hiaFNupfzfbHQntb2puU7e4KFVyjxa6jmvivEQAqAnMQq1gZXsmIpwa/WpK/crEHI+U1lmxofHGB9OlufWsLihfwUTx0tni93ejzW9lm2AFQou0wb6ikbVnMG3H8OSyAUlYzdqjibBRiH1PJITEF5jmtgfB/gXweUCpITYx6H1g2v5PVRkZc="
#  - secure: "SoovFaVjC32qyVnqSiwI2d6oJ+H3gKtisWwXd8lheDVSJ7UVPrOgyBugcnuuVffqPZdBIBfG7IjEYqrWNrl1rfJcqhxZbIbG0Pi004bos/tJIA1nQCcS2zgY8w+edKTFfKdncs9BgnoMXFL2EYwq91S5QGN2sZ5B0ovLiKQAavo52tz/B+p/cJg/+gOfMs4Q6FaDbDavaBX/3PW4+x4TydqtJ36m8TFzmqj0VFXwZW5AgyO/L24XJUqlEUL/CIZKtfwk29PdKf+Jm1MmK8Vmrp6I6NFx13wu07K6eX/qpAtfo/weK7ffz02FbCdsn0LEowgnHb3zH4AUHGYjgaxMrvZiWsXC/85btY2TpFR591TVIAzbCZXlELCeXUyCiPN1A61a3WXQewbtAls4+2NZqM9K/f+UOzHtxjRqPA9WKT8AxhgMhJbh/BGrATa5EgrGJxNAf3RACUTRAHWOXVfmltErUw+pd7eaAFivcwQCKqm2S0hd1Tat3dqb3sW23uyF9FnQMlJIh0nv5fKu/XvQ4B8fOrRh9Owqk8rC5VPJNjhLONZwxMRtvgnlG3Aw1T4AQ4+bLTMWHtqH41vfh07ByZ2vYZlTJu1yf4wmcNAHTK5PnM2cJ3TTE+w+Qw+iw27bXADGB+EPZlSG9FbSazR4brMg9dKi4tTgvSSxDckNwmQ="
#  - secure: "TaCM9QXWnGaUQijGrK34uid9BCUpLC1nF6HuSJg95m2QzoqQJZDBLYv2qD3SD91DwCM7iFlrCABTEDO6m9qT5D+lGpmnDWSJvI20o9bUwKfIM1TWc4HGVyRurvQUuYaYu9sC0pYjDOBZo6lBVGXG4+6NeFtdEBzGkV+OnN80TbcMxZU25p1R/H0CFDzAe20HlyN9hVSBe1cAFE8fw2dY4t87eAbbLNh3KwhMK++Gct8xzK+cbBc9D0YfhO585lvE4N379C/JiI4oNS77mIqdXYztz/cKTAfbU6AB0efgKy9BpexcdLQp4wnVGzI6stew/f63Gu0rXMvwXqbtjVNKP9Bn9yHnAloKM5RkhnZp+/tEIrW/kSitEOLOSkxecRJyakX6uFSkxycoupW8pP/bXpqLoIKU3TaK/tSNm1sWLsCTBuas6xNcjALUxk7qeN6GZ7svfUu6abJCdTtnkw7l/EdjstvEASkeoGQwmIBbaUwbOMvpD5Ge/1U5cmwEEdoYUS6//9iIAkJohgeALtzjvZCmo3jBoIfqmZZafAhiI2ZnFQxhAsceF1Ncx8ktxYSqhXSpfJoEIT90rimZVux7ay7mvmGv4SmIWAGNs1x0Zs8V+An537eyntrtYi/mjeYwHOkGcFXTtiS/RnAHtf0KwR/Xeidt0nLUoUjqXf1hkCA="
  - secure: i/esKc15i8+lkbYltwysLRB9WGr3PxIIZrF+P5LLOyX2xlunxMpPEqhLoVagwfFZQ8E6EUzb2p6OOum1M5Cnd/l0fRHoUS9VcJtzfhqj1uZgWvBhJF8WgMv9US5Zpmnv3xE/Zzz5FdCsPZThs7N53Sy3xwYwGfAchEh1YnDDzvcLcEBOvAmMbGNrGthIbs9tF94cWtrzsIUH2Tel4WkA+IfWNXO+6omhUd+xNTk3TZgZfCU/hTPEv7Y79gr7DLmEQvwC+5a3zVwgHWiv3Rb/j7dUHU13EdJeIH4gsy/KkGKW9cUEv5ov4oKU3drHxqa+4/4PjSwlBMnsjE7J8KqVikR6HKL/0siuc/yjC2O66ddqheJf1K9ndPKhNAoMSGcPIGrPA76IOIQJyROBNX+MxXThTo+6gkwtfq+cqzbbCDmIojuyJPDIKvZb8XIXaVaMr6Ms93hMscRQynn92ArQ5BGRkCflr2ZOjerkO8b1jqyuBqJaljmOuBql7JIznCXdPkgQ3ZBM26l73oGbVGRT7u3uBxuOJuNi6cXq1gEI8N6MKnnEATzZYM8AOV3sWJrS34uw9jW/E6pJbw6uTj7d6ZmZ1mZhODMAjM36mGGV45c8WhG84Pkaye/ZKgIqXXb7+QMTp6X+1tqRHHPx8NdUVb88nWQtsLtWbFQVELLd0aw=

deploy:
  provider: pages
  skip-cleanup: true
  # travis encrypt GITHUB_TOKEN=<your github repo token> --add
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
  local-dir: target/generated-docs
  target_branch: gh-pages
