notifications:
  email: false
git:
  quiet: true
  depth: false
language: java
jdk: openjdk8
node_js: lts/*
python: 3.7
matrix:
  include:
    - python: 3.7
services:
  - xvfb
  - docker
addons:
  apt:
    update: false
    packages:
      - jq
      - bash
      - curl
      - tree
      - docker-ce
      - libxml2-utils
      - libappindicator1
      - fonts-liberation
      - google-chrome-stable
      - python3-setuptools
      - python3-pip
install: true
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  #
  - if [ ! -f ${HOME}/.local/daggerok/bash-functions/master/main.bash ] ; then
    mkdir -p ${HOME}/.local/daggerok/bash-functions/master ;
    curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash > ${HOME}/.local/daggerok/bash-functions/master/main.bash ;
    fi
  - source ${HOME}/.local/daggerok/bash-functions/master/main.bash
  - stop_any 80 5432 8080 6551
  #
  - export PATH=$HOME/.local/bin:$PATH
  - pip3 install --user --upgrade pip
  - pip install --user --upgrade httpie docker-compose
env:
  global:
    - TERM=dumb
jobs:
  include:
    - stage: test
      name: spring-security-oauth2-jwt step-1
      jdk: openjdk11
      before_script:
        - cp -Rf $TRAVIS_BUILD_DIR/spring-security-oauth2-jwt/step-1-basic/src/main/resources/disabled.application-fb.yaml $TRAVIS_BUILD_DIR/spring-security-oauth2-jwt/step-1-basic/src/main/resources/application-fb.yaml
      script:
        - cd $TRAVIS_BUILD_DIR/ && ./mvnw -f spring-security-oauth2-jwt/step-1-basic/
        - java -jar $TRAVIS_BUILD_DIR/spring-security-oauth2-jwt/step-1-basic/target/*.jar &
        - wait_for 8080
        - http -a admin:admin :8080
        - http -a user:password :8080/api/greeting
        - stop_any 80 8080
    - stage: test
      name: spring-security-oauth2-jwt step-0
      jdk: openjdk11
      script:
        - cd $TRAVIS_BUILD_DIR/ && ./mvnw -f spring-security-oauth2-jwt/step-0
        - java -jar $TRAVIS_BUILD_DIR/spring-security-oauth2-jwt/step-0/target/*.jar &
        - wait_for 8080
        - http :8080
        - http :8080/api/greeting
        - stop_any 80 8080
    - stage: test
      jdk: openjdk8
      name: spring-mvc-facebook
      script:
        - cp -Rf $TRAVIS_BUILD_DIR/spring-5-security-oauth2/spring-mvc-facebook/src/main/resources/application-oauth2-default.yaml $TRAVIS_BUILD_DIR/spring-5-security-oauth2/spring-mvc-facebook/src/main/resources/application-oauth2.yaml
        - cd $TRAVIS_BUILD_DIR/ && bash ./gradlew -Pci -b $TRAVIS_BUILD_DIR/spring-5-security-oauth2/build.gradle >/dev/null
        - java -jar $TRAVIS_BUILD_DIR/spring-5-security-oauth2/spring-mvc-facebook/build/libs/*.jar &
        - wait_for 8080
        - http :8080/login
        - stop_any 8080 80
    - stage: test
      jdk: openjdk8
      name: spring-mvc-facebook-github
      befoe_script:
        - cp -Rf $TRAVIS_BUILD_DIR/spring-5-security-oauth2/spring-mvc-facebook-github/src/main/resources/application-oauth2-default.yaml $TRAVIS_BUILD_DIR/spring-5-security-oauth2/spring-mvc-facebook-github/src/main/resources/application-oauth2.yaml
      script:
        - cd $TRAVIS_BUILD_DIR/ && bash ./gradlew -Pci -b $TRAVIS_BUILD_DIR/spring-5-security-oauth2/build.gradle >/dev/null
        - cd $TRAVIS_BUILD_DIR/ && bash $TRAVIS_BUILD_DIR/spring-5-security-oauth2/spring-mvc-facebook-github/build/libs/*.jar &
        - wait_for 8080
        - http :8080/login
        - stop_any 8080 80
    - stage: test
      jdk: openjdk8
      name: spring-mvc-github
      before_script:
        - cp -Rf $TRAVIS_BUILD_DIR/spring-5-security-oauth2/spring-mvc-github/src/main/resources/application-oauth2-default.yaml $TRAVIS_BUILD_DIR/spring-5-security-oauth2/spring-mvc-github/src/main/resources/application-oauth2.yaml
      script:
        - cd $TRAVIS_BUILD_DIR/ && bash ./gradlew -Pci -b $TRAVIS_BUILD_DIR/spring-5-security-oauth2/build.gradle >/dev/null
        - cd $TRAVIS_BUILD_DIR/ && bash $TRAVIS_BUILD_DIR/spring-5-security-oauth2/spring-mvc-github/build/libs/*.jar &
        - wait_for 8080
        - http :8080/login
        - stop_any 8080 80
#    - stage: test
#      jdk: openjdk8
#      name: web-driver-security-testing
#      script:
#        - cd $TRAVIS_BUILD_DIR/ && bash $TRAVIS_BUILD_DIR/web-driver-security-testing/mvnw -f $TRAVIS_BUILD_DIR/web-driver-security-testing/ >/dev/null
#        - java -jar $TRAVIS_BUILD_DIR/web-driver-security-testing/target/*.jar &
#        - wait_for 8080
#        - http :8080
#        - http :8080/login
#        - http -a usr:pwd :8080/
#        - sleep 1s
#        - stop_any 80 8080
    - stage: test
      jdk: openjdk8
      name: web-mvc-security-testing-with-mock-user
      script:
        - cd $TRAVIS_BUILD_DIR/ && bash $TRAVIS_BUILD_DIR/web-mvc-security-testing-with-mock-user/mvnw -f $TRAVIS_BUILD_DIR/web-mvc-security-testing-with-mock-user/pom.xml >/dev/null
        - java -jar $TRAVIS_BUILD_DIR/web-mvc-security-testing-with-mock-user/target/*.jar &
        - wait_for 8080
        - http :8080
        - http :8080/login
        - http -a usr:pwd :8080/
        - sleep 1s
        - stop_any 80 8080
    - stage: test
      jdk: openjdk8
      name: keycloak-identity-management
      script:
        - cd $TRAVIS_BUILD_DIR/keycloak-identity-management && ./gradlew clean assemble >/dev/null
        - cd $TRAVIS_BUILD_DIR/keycloak-identity-management && ./gradlew composeUp >/dev/null
        - cd $TRAVIS_BUILD_DIR/keycloak-identity-management && ./gradlew composeDown
    - stage: test
      jdk: openjdk8
      name: csrf-protection-spa
      script:
        - cd $TRAVIS_BUILD_DIR/csrf-protection-spa && ./gradlew clean assemble >/dev/null
        - cd $TRAVIS_BUILD_DIR/csrf-protection-spa && ./gradlew composeUp >/dev/null
        - cd $TRAVIS_BUILD_DIR/csrf-protection-spa && ./gradlew composeDown
    - stage: deploy
      jdk: openjdk8
      name: GitHub Pages
      env:
        - TERM=dumb
        - secure: "GrR/PL1J30gnVuxzVNB77gQiuQ8d0oKGCEA8SOj/I2+RxqoRcepSPQjNTdZzLOwJ/ZeiyoWTKaFIgqL8SvZlnEjLMgF8VL1Yb5dKLQNFBNcZhQWgvd91T155wGmqWFJU0ZUio5mKljlMmtOYyI3+sLb/kSnoAuqGmfHITo10zetOpePU+9x64TJOUEjBRcw82m+1biuWQiyj/0c1pZHjM98jF1TV9c6ck1xwKgp3TLeJA23/eEkmZgnocf8HlWLlMgRIMXeF6pDzU6zVb89/M+l1mCfRAswLPARBGZUGH31XJIK2xwztssQBC/MX4FhLnurzOz5B5nzuJguIIdSytrtq0X7s3TbhiAclylv1fC8P55s+oQywKZPTs3/SZrltqK+eEAySTEhoxoGE85NXWyiA3vt2tsqdUnDidEoNehbIWW8UdIM6DeDNdC4gTMnkIBUssI90vCA3dTNwarMrcfDAfIhkidhq0ysi/ey94I2ZJ+B68hFMuyWbaIykrZGLfRaknldfVdWee2AAZdPtq6IR15fhgR1PwImWEpNYQHpvszLlQ1JO6Rlm3E0VWqXd4MRFghklAjsh1suKYLy6+v9WTZfwhQBJo7cCTgb2wwnQdf992M4VqlRUiCiJmmSsFs4OjHQ2O4vc/uHPh7OO1eUAkiiVYfaAFTYOiu/HYak="
      before_deploy:
        - cd $TRAVIS_BUILD_DIR/
        - ./gradlew --stop
        - ./mvnw -Pdocs
      deploy:
        provider: pages
        skip-cleanup: true
        # travis encrypt GITHUB_TOKEN=<your github repo token> --add
        github-token: "$GITHUB_TOKEN"
        keep-history: true
        on:
          branch: master
        local-dir: target/generated-docs
        target_branch: gh-pages
before_cache:
  - find ~/.gradle -name "fileHashes.bin" -print0 | xargs -0 rm -rfv '{}'
  - for item in $(find ~/.gradle -name "*.lock") ; do rm -rfv $item ; done
cache:
  pip: true
  packages: true
  directories:
    - ~/.m2
    - ~/.gradle
    - ~/.docker
