# keytool -genkey -alias tomcat -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
## password: password
## keytool -list -v -keystore keystore.p12 -storetype pkcs12
---
spring:
  profiles:
    active: ssl
server:
  port: 8443
  ssl:
    key-store: classpath:ssl/keystore.p12
    key-password: password
    key-store-password: ${server.ssl.key-password}
---
