version: "2.1"

services:

  gradle-spring-5-security-oauth2-app:
    build:
      context: .
      dockerfile: gradle/Dockerfile
    volumes: ["gradle-spring-5-security-oauth2-app-data:/home/appuser"]
    networks: [backing-services]
    ports: ["8080:8080"]
    restart: unless-stopped
    mem_limit: 838860800 # container limit: 200Mb (200 * 1024 * 1024)

volumes:
  gradle-spring-5-security-oauth2-app-data: {}

networks:
  backing-services:
    driver: bridge
